// Datos iniciales reales de la tienda Herboristería Pasaje.
// formato: v(linea, unidad, categoria, [[sabor, stock], ...]) y s(nombre, categoria, unidad, stock)
// stock 0 = sin stock (marcado con X en la lista original)

export const CATEGORIES = [
  { name: "Proteínas", slug: "proteinas" },
  { name: "Ganadores de masa", slug: "ganadores" },
  { name: "Creatina", slug: "creatina" },
  { name: "Aminoácidos y BCAA", slug: "aminoacidos" },
  { name: "Pre-entrenos y energía", slug: "preentrenos" },
  { name: "Quema-grasas y control de peso", slug: "quemagrasas" },
  { name: "Vitaminas y minerales", slug: "vitaminas" },
  { name: "Omega y ácidos grasos", slug: "omega" },
  { name: "Plantas medicinales y herbolario", slug: "plantas" },
  { name: "Colágeno y articulaciones", slug: "colageno" },
  { name: "Digestión y probióticos", slug: "digestion" },
  { name: "Descanso y bienestar", slug: "descanso" },
  { name: "Alimentación para perros", slug: "perros" },
  { name: "Alimentación para gatos", slug: "gatos" },
  { name: "Higiene, cosmética y otros", slug: "otros" },
];

const v = (line, unit, cat, flavors) =>
  flavors.map(([f, s]) => ({ name: `${line} ${f}`.replace(/\s+/g, " ").trim(), unit, cat, stock: s }));
const s = (name, cat, unit = "", stock = 0) => ({ name, unit, cat, stock });

export const BRANDS = [
  {
    brand: "REVER",
    items: [
      ...v("ISO90 2KG", "2 kg", "proteinas", [["Fresa/Plátano", 0], ["Fresa", 0], ["Chocolate", 3], ["Chocolate blanco", 0], ["Cookies", 0], ["Cookies Royal", 3], ["Limón", 0], ["Hel. Vainilla", 2], ["Ferrero", 3], ["KitKat", 0]]),
      ...v("WHEY 2KG", "2 kg", "proteinas", [["Fresa/Plátano", 2], ["Fresa", 2], ["Chocolate", 3], ["Chocolate blanco", 1], ["Cookies", 3], ["Hel. Vainilla", 0], ["Limón", 1], ["Ferrero", 2], ["KitKat", 1], ["Cookies Royal", 1]]),
      ...v("ISO 1KG", "1 kg", "proteinas", [["Chocolate", 1], ["Chocolate blanco", 1], ["Fresa", 3], ["Fresa/Plátano", 4], ["Limón", 1], ["Vainilla", 3], ["Cookies", 1], ["Cookies Royal", 1], ["Ferrero", 1], ["KitKat", 0]]),
      ...v("WHEY 1KG", "1 kg", "proteinas", [["Chocolate blanco", 2], ["Chocolate", 0], ["Vainilla", 2], ["Fresa", 4], ["Cookies", 0], ["Cookies Royal", 2], ["Fresa/Plátano", 4], ["Limón", 1], ["KitKat", 2], ["Ferrero", 1]]),
      ...v("GAINERS 3KG", "3 kg", "ganadores", [["Cookies", 2], ["KitKat", 1], ["Vainilla", 0], ["Chocolate", 1], ["Chocolate blanco", 0], ["Ferrero", 1], ["Fresa", 0]]),
      ...v("GAINERS 1KG", "1 kg", "ganadores", [["Cookies", 2], ["KitKat", 0], ["Vainilla", 1], ["Chocolate", 2], ["Chocolate blanco", 0], ["Ferrero", 0], ["Fresa", 2]]),
      ...v("CREATINA 300GR", "300 g", "creatina", [["Neutra", 4], ["Limón", 5], ["Naranja", 4], ["Piruleta", 6], ["Shaker", 8]]),
    ],
  },
  {
    brand: "REVER CASA",
    items: [
      ...v("ISO90 2KG", "2 kg", "proteinas", [["Fresa/Plátano", 0], ["Fresa", 0], ["Chocolate", 0], ["Chocolate blanco", 0], ["Cookies", 0], ["Cookies Royal", 1], ["Limón", 1], ["Hel. Vainilla", 1], ["Ferrero", 3], ["KitKat", 1]]),
      ...v("WHEY 2KG", "2 kg", "proteinas", [["Fresa/Plátano", 2], ["Fresa", 0], ["Chocolate", 0], ["Chocolate blanco", 0], ["Cookies", 0], ["Hel. Vainilla", 2], ["Limón", 0], ["Ferrero", 0], ["KitKat", 0], ["Cookies Royal", 0]]),
      ...v("ISO 1KG", "1 kg", "proteinas", [["Chocolate", 1], ["Chocolate blanco", 0], ["Fresa", 0], ["Fresa/Plátano", 0], ["Limón", 1], ["Vainilla", 1], ["Cookies", 0], ["Cookies Royal", 0], ["Ferrero", 0], ["KitKat", 0]]),
      ...v("WHEY 1KG", "1 kg", "proteinas", [["Chocolate blanco", 0], ["Chocolate", 0], ["Vainilla", 0], ["Fresa", 0], ["Cookies", 0], ["Cookies Royal", 0], ["Fresa/Plátano", 0], ["Limón", 0], ["KitKat", 3], ["Ferrero", 0]]),
      ...v("GAINERS 3KG", "3 kg", "ganadores", [["Chocolate blanco", 1], ["KitKat", 1], ["Cookies", 1], ["Ferrero", 1], ["Chocolate", 1], ["Vainilla", 1]]),
      s("Creatina 300gr", "creatina", "300 g", 17),
    ],
  },
  {
    brand: "ESSENTIAL NUTRICIÓN",
    items: [
      ...v("ISO2KG", "2 kg", "proteinas", [["Vainilla/Canela", 1], ["Hel. Limón", 0], ["Chocolate", 1], ["Chocolate blanco", 0], ["Ferrero", 1], ["Chocolate Car. Cookies", 0], ["Hel. Vainilla", 0], ["Cookies", 1], ["Tarta de Chocolate", 0], ["Donuts", 0], ["Donuts Chocolate Blanco", 0], ["Piña", 2], ["KitKat", 1], ["Fresa", 2], ["Fresa/Plátano", 0], ["Plátano", 0], ["Oreo", 0]]),
      ...v("WHEY2KG", "2 kg", "proteinas", [["Hel. Vainilla", 0], ["Hel. Limón", 1], ["Piña", 2], ["Cookies", 0], ["Chocolate", 0], ["Ferrero", 0], ["Oreo", 1], ["Donuts Chocolate", 0], ["Chocolate blanco", 1], ["KitKat", 0], ["Donuts", 1], ["Choco Avellana", 1], ["Plátano", 1], ["Fresa", 0], ["Fresa/Plátano", 1], ["Vainilla/Canela", 1]]),
      ...v("CASEÍNA 1KG", "1 kg", "proteinas", [["Chocolate", 0], ["Fresa", 1], ["Vainilla", 0], ["Fresa/Plátano", 0]]),
      ...v("JUNGLE 1.5KG", "1.5 kg", "proteinas", [["Agar Hair", 0]]),
      ...v("MAP 350GR", "350 g", "aminoacidos", [["Melocotón", 0], ["Naranja", 2], ["Cola", 0], ["Piruleta", 3]]),
      ...v("WAZY MAIZE", "700 g", "ganadores", [["Frutos del Bosque", 1], ["Neutro", 2], ["Limón", 0]]),
      ...v("ISO1KG", "1 kg", "proteinas", [["Donuts", 0], ["Ferrero", 2], ["Fresa/Plátano", 2], ["Limón", 2], ["Hel. Vainilla", 1], ["Chocolate Avellana", 0], ["Chocolate Blanco", 2], ["Vainilla Canela", 1], ["Cookies Car. Chocolate", 0], ["Fresa", 2], ["Donuts Chocolate", 0], ["KitKat", 0], ["Piña", 2], ["Oreo", 0], ["Plátano", 2], ["Cookies", 0], ["Chocolate", 1], ["Donuts Chocolate Blanco", 0]]),
      ...v("WHEY 1KG", "1 kg", "proteinas", [["Donuts Chocolate", 0], ["Piña", 1], ["Donuts", 0], ["Chocolate", 0], ["Cookies", 0], ["Ferrero", 0], ["KitKat", 0], ["Hel. Limón", 2], ["Fresa/Plátano", 2], ["Tarta Chocolate", 0], ["Donuts Chocolate Blanco", 0], ["Choco Avellana", 0], ["Chocolate Blanco", 0], ["Vainilla Canela", 0], ["Hel. Vainilla", 0], ["Fresa", 2], ["Cookies Choc. Caramelo", 0], ["Oreo", 2], ["Plátano", 0]]),
      ...v("GAINERS", "2.5 kg", "ganadores", [["Chocolate", 0], ["Cookies", 0], ["Fresa", 0], ["Vainilla Canela", 0], ["Chocolate Blanco", 0], ["Fresa/Plátano", 0], ["7kg Fresa/Plátano", 0], ["7kg Vainilla", 0]]),
      s("Acetil L-Carnitina", "quemagrasas", "", 0),
      s("Carnipure 120", "quemagrasas", "120 cápsulas", 6),
      s("Senefrina", "quemagrasas", "", 10),
      s("Cafeína", "preentrenos", "", 3),
      s("Omega 3 60", "omega", "60 cápsulas", 1),
      s("Omega 90", "omega", "90 cápsulas", 10),
      s("Water", "otros", "", 3),
      s("Multivitamínico", "vitaminas", "", 6),
      s("Burn Core 30C", "quemagrasas", "30 cápsulas", 7),
      s("Burn Core 90C", "quemagrasas", "90 cápsulas", 9),
      s("Testo 90", "quemagrasas", "", 6),
      s("Pic. Cromo", "quemagrasas", "", 15),
      s("L-Carnitina Limón", "quemagrasas", "", 0),
      ...v("CREAPURE 300GR", "300 g", "creatina", [["Piruleta", 0], ["Neutra", 0], ["Neutra 500gr", 0]]),
      ...v("CREATINA 400GR", "400 g", "creatina", [["Limón", 11], ["Naranja", 6], ["Piruleta", 0], ["Neutra", 12], ["Neutra 100gr", 3], ["Piruleta 100gr", 0], ["Limón 100gr", 1]]),
      s("Cronapure 300GR", "creatina", "300 g", 13),
      s("Té Verde", "preentrenos", "", 2),
      s("Ciclodextrina Limón", "ganadores", "", 0),
      s("Ciclodextrina Neutra", "ganadores", "", 2),
      s("ZMA", "vitaminas", "", 2),
      s("Tribulus", "quemagrasas", "", 11),
      s("Arginina Caps.", "aminoacidos", "", 2),
      s("One 30C", "otros", "30 cápsulas", 1),
      s("One 90C", "otros", "90 cápsulas", 5),
      s("NAC", "digestion", "", 8),
      s("Vitamina C 1gr", "vitaminas", "1 g", 12),
      s("Beta-Alanina Polvo", "preentrenos", "", 3),
      ...v("NOX", "500 g", "preentrenos", [["Piruleta", 5], ["Cola", 2], ["Naranja", 6]]),
      ...v("GLUTAMINA 400GR", "400 g", "aminoacidos", [["Neutra", 2], ["Fresa", 3], ["Fresa 250gr", 4]]),
      s("Citrunila Polvo", "aminoacidos", "", 0),
      s("Gummy Melato", "descanso", "", 12),
      s("Ashwagandha Sensoril", "plantas", "", 6),
      s("Arginina Polvo", "aminoacidos", "", 2),
      s("Deep Heat", "otros", "", 2),
      s("Radian", "otros", "", 7),
      ...v("BCAA", "400 g", "aminoacidos", [["Blue Tropic", 6], ["Limón", 1], ["Piña Colada", 2]]),
      ...v("BCAA+GLUTA", "400 g", "aminoacidos", [["Limón", 1], ["Piruleta", 0], ["Piña Colada", 0], ["Blue Tropic", 0]]),
      ...v("PUMP", "400 g", "preentrenos", [["Tropical", 2], ["Sandía", 2], ["Lima", 0]]),
      s("CLA", "quemagrasas", "", 10),
      s("Berberina", "digestion", "", 4),
      s("Vitamina E", "vitaminas", "", 10),
      s("R-ALA", "quemagrasas", "", 8),
      s("EAA + Glutamina Limón", "aminoacidos", "", 8),
      s("EAA + Naranja", "aminoacidos", "", 3),
      s("Bisglicinato Magnesio", "vitaminas", "", 9),
      s("Saw Palmeto", "plantas", "", 3),
      ...v("PROTEÍNA VEGETAL", "500 g", "proteinas", [["Fresa", 0], ["Natillas con Galletas", 3], ["Chocolate", 2]]),
      s("X-Drol", "quemagrasas", "", 0),
      s("Vitamina D3+K2", "vitaminas", "", 7),
      s("Maca 90C", "plantas", "90 cápsulas", 5),
      s("Colágeno 300gr Piña", "colageno", "300 g", 16),
      s("Colágeno Limón", "colageno", "", 7),
      s("Probiótico", "digestion", "", 2),
      ...v("BCAA+GLUTA 350GR", "350 g", "aminoacidos", [["Piruleta", 6], ["Melocotón", 4], ["Cola", 0], ["Naranja", 4]]),
      s("Ecdysterone", "quemagrasas", "", 0),
      s("Vitamina B", "vitaminas", "", 2),
    ],
  },
  {
    brand: "NATURMIL",
    items: [
      s("Resveratrol 9-18", "plantas", "", 5),
      s("Espirulina 6-12", "vitaminas", "", 0),
      s("Krill 9-18", "omega", "", 6),
      s("Zinc 4-7", "vitaminas", "", 1),
      s("K2 7-18", "vitaminas", "", 2),
      s("Ashwagandha 5-12-2", "plantas", "", 0),
      s("Astaxantina 7-15", "vitaminas", "", 1),
      s("Vitamina E 7-18", "vitaminas", "", 0),
      s("Vitamina A 3-8", "vitaminas", "", 2),
      s("NADH 8-15", "vitaminas", "", 7),
      s("B12 6-15", "vitaminas", "", 0),
      s("Lisina 4-12", "aminoacidos", "", 3),
      s("Biotina 7-15", "vitaminas", "", 3),
      s("Valeriana 3-6", "plantas", "", 0),
      s("Hair & Nails 6-12", "vitaminas", "", 5),
      s("MSM 6-15", "colageno", "", 2),
      s("Betacaroteno 4-10", "vitaminas", "", 4),
      s("Ácido Hialurónico 8-15", "colageno", "", 0),
      s("Malato Magnesio 15", "vitaminas", "", 0),
      s("Colágeno + Magnesio 180 6-12", "colageno", "", 0),
      s("Castaño de Indias 4-7", "plantas", "", 5),
      s("Aminoácidos 10-15", "aminoacidos", "", 2),
      s("Glutamina", "aminoacidos", "", 1),
      s("L-Treonato 21-45", "vitaminas", "", 2),
      s("BCAA", "aminoacidos", "", 0),
      s("Hinojo 4-7", "plantas", "", 0),
      s("Niacina", "vitaminas", "", 1),
      s("Rhodiola 8-15", "plantas", "", 4),
      s("Centella Asiática 4-7", "plantas", "", 2),
      s("Ácido Fólico", "vitaminas", "", 3),
      s("Graviola", "plantas", "", 1),
      s("Vitamina D3", "vitaminas", "", 1),
      s("Tirosina 5-10", "aminoacidos", "", 3),
      s("Creatina", "creatina", "", 6),
    ],
  },
  {
    brand: "ELADIET",
    items: [
      s("Gases", "digestion", "", 0),
      s("HerbalFrio", "digestion", "", 0),
      s("Aceite de Ricino 6-10", "otros", "", 0),
      s("Melena de León 11-20", "plantas", "", 3),
      s("Lindaren 3-6", "descanso", "", 1),
    ],
  },
  {
    brand: "DRASANVI",
    items: [
      s("Vitaminolas 6-12", "vitaminas", "", 0),
      s("Vitamina C Gummies 6-12", "vitaminas", "", 1),
      s("B12 6-12", "vitaminas", "", 0),
      s("Vinagre de Manzana Gummy 6-12", "digestion", "", 0),
      s("Próstata 8.5-17", "plantas", "", 0),
      s("Shilajit 12-24", "vitaminas", "", 2),
      s("Ashwagandha Gummy 9-18", "plantas", "", 4),
      s("Retinol Vit. A 5-12", "vitaminas", "", 3),
      s("Citrato Magnesio Gummies 7-12", "vitaminas", "", 6),
    ],
  },
  {
    brand: "YNSADIET",
    items: [
      s("Orégano 4-12", "plantas", "", 2),
      s("Máster 10-18", "digestion", "", 14),
      s("Maca Plus 12", "plantas", "", 0),
      s("AstroCalm 14-20", "descanso", "", 9),
    ],
  },
  {
    brand: "PINISAN",
    items: [
      s("Kowi Flex", "colageno", "", 0),
      s("Kowi Relax", "descanso", "", 0),
      s("Kowi Gastric", "digestion", "", 2),
      s("CBD", "descanso", "", 5),
      s("Uricalm", "digestion", "", 0),
      s("Neurodrop", "descanso", "", 0),
      s("Vitamina B", "vitaminas", "", 3),
      s("Citrato Magnesio", "vitaminas", "", 14),
      s("Magnesio + Potasio", "vitaminas", "", 15),
      s("Vitamina C 12-8", "vitaminas", "", 7),
      s("Colágeno + MG Frutos del Bosque", "colageno", "", 0),
      s("Digesan", "digestion", "", 0),
      s("Bronce Activ", "otros", "", 0),
      s("Articao", "colageno", "", 19),
      s("ArtBikrem", "colageno", "", 0),
      s("Bikrem Cáñamo", "colageno", "", 0),
      s("Cola de Caballo", "plantas", "", 8),
      s("Alcachofa", "digestion", "", 7),
      s("Valeriana", "descanso", "", 0),
      s("Mela Retard", "descanso", "", 6),
      s("Canela", "digestion", "", 0),
      s("Cúrcuma", "digestion", "", 7),
      s("Uriprostat", "plantas", "", 0),
      s("Arándano", "digestion", "", 3),
      s("Uriscit", "digestion", "", 0),
      s("Nivesterol", "quemagrasas", "", 3),
      s("Hepátic", "digestion", "", 4),
      s("Colagen Top", "colageno", "", 38),
      s("Cup 28c", "vitaminas", "28 cápsulas", 3),
      s("Cardo Mariano", "digestion", "", 0),
      s("Bidfisan", "digestion", "", 1),
      s("Griffonia 6+4", "descanso", "", 0),
      s("Maca", "plantas", "", 0),
      s("Ashwagandha", "plantas", "", 2),
      s("Germen de Trigo", "vitaminas", "", 5),
      s("Redefine", "quemagrasas", "", 2),
      s("Vitamina Caps.", "vitaminas", "", 3),
      s("Bisglicinato Magnesio-7", "vitaminas", "", 2),
      s("Magnesio Total", "vitaminas", "", 0),
      s("Energisan", "preentrenos", "", 0),
      s("Total Polvo", "digestion", "", 5),
      s("Ginkgo", "plantas", "", 9),
      s("Lax", "digestion", "", 2),
      s("Femepausia", "descanso", "", 0),
      s("Farimpol", "digestion", "", 0),
      s("Propóleo Ext.", "digestion", "", 1),
      s("Inmunisan", "digestion", "", 1),
      s("Adiós Pañuelo", "digestion", "", 0),
      s("A Comer", "digestion", "", 0),
      s("Dulces Sueños", "descanso", "", 2),
      s("A Dormir", "descanso", "", 3),
      s("Cellup", "quemagrasas", "", 1),
      s("Kemaline Caps.", "digestion", "", 17),
      s("Equinácea Complex Gotas", "digestion", "", 1),
      s("Drenaxtrem", "digestion", "", 1),
      s("Equinácea Caps.", "digestion", "", 0),
      s("Q10", "vitaminas", "", 0),
      s("Vientre Plano", "digestion", "", 1),
      s("Relax Calm", "descanso", "", 5),
      s("Poliar On", "quemagrasas", "", 5),
      s("Harpago", "colageno", "", 0),
      s("Omega 3", "omega", "", 5),
      s("Garcinia + Triptófano", "quemagrasas", "", 0),
      s("Adilpic", "digestion", "", 0),
      s("Muscurelax", "descanso", "", 3),
      s("NAD+", "vitaminas", "", 9),
      s("Vitamina C Liposomada", "vitaminas", "", 6),
      s("Vitamina D3 Liposomada", "vitaminas", "", 2),
      s("Sueños Plus", "descanso", "", 9),
      s("Vitalys", "vitaminas", "", 8),
      s("Ashwagandha + MG", "plantas", "", 0),
    ],
  },
  {
    brand: "PLAMECA",
    items: [
      s("Plamepil", "digestion", "", 15),
      s("Perlavida", "digestion", "", 0),
      s("Tribiotic", "digestion", "", 1),
      s("Jugo de Aloe", "digestion", "", 6),
      s("Gel de Aloe", "otros", "", 7),
      s("Vitamina D3+K2", "vitaminas", "", 2),
      s("Melanoctina Bicapa", "descanso", "", 2),
      s("Melatonina 30", "descanso", "30 cápsulas", 3),
      s("Menstrual", "descanso", "", 2),
      s("Menopausia", "descanso", "", 2),
      s("Melatonina 60", "descanso", "60 cápsulas", 0),
      s("Triptófano", "descanso", "", 4),
      s("Venalight Caps.", "otros", "", 0),
      s("Venalight Crema", "otros", "", 16),
      s("Laxoflah", "digestion", "", 1),
      s("Omega 3-2", "omega", "", 0),
      s("Magnesio + Curcumán", "digestion", "", 1),
      s("Policol", "quemagrasas", "", 15),
      s("Normatens 9e", "plantas", "", 2),
      s("Digestisimo", "digestion", "", 1),
      s("Curarti 30c", "colageno", "30 cápsulas", 1),
      s("Curarti 60c", "colageno", "60 cápsulas", 12),
      s("Mela Spray", "descanso", "", 0),
      s("Mela Gota", "descanso", "", 4),
      s("Curarti Colagtium", "colageno", "", 0),
      s("Diudren", "digestion", "", 0),
      s("Ber-Detox", "digestion", "", 0),
      s("Curarti Colagtium Pol. Neutro", "colageno", "", 4),
      s("Curarti Complex Pol. Limón", "colageno", "", 3),
      s("Curarti Complex", "colageno", "", 0),
      s("Memory", "descanso", "", 0),
      s("Onaprim 200p", "digestion", "", 1),
      s("Protectium Jarabe", "digestion", "", 2),
      s("Propol Infantil", "digestion", "", 1),
      s("Multivitamínico", "vitaminas", "", 12),
      s("Laxofruits", "digestion", "", 7),
      s("Mela Bicapa Trastero", "descanso", "", 7),
      s("Curarti F.60", "colageno", "", 22),
    ],
  },
  {
    brand: "NATURE VARIETY",
    items: [
      s("Pollo Original", "perros", "12 kg", 0),
      s("Pollo", "perros", "12 kg", 1),
      s("Salmón", "perros", "12 kg", 1),
      s("Puppy Salmón", "perros", "12 kg", 0),
      s("Mini Puppy 7kg", "perros", "7 kg", 0),
      s("Pavo Original", "perros", "12 kg", 1),
      s("Pescado Blanco", "perros", "12 kg", 0),
      s("Cat Salmón 7k", "gatos", "7 kg", 0),
      s("Cat Pavo 7k", "gatos", "7 kg", 0),
      s("Cat Pollo No Grain", "gatos", "7 kg", 0),
    ],
  },
  {
    brand: "NUTRIBEST",
    items: [
      s("Salmón", "perros", "12 kg", 0),
      s("Pollo", "perros", "12 kg", 0),
      s("Lamb", "perros", "12 kg", 0),
      s("Cerdo", "perros", "12 kg", 0),
      s("Puppy Pollo", "perros", "12 kg", 0),
      s("Puppy Salmón", "perros", "12 kg", 0),
      s("Mini", "perros", "3 kg", 1),
      s("Light", "perros", "12 kg", 1),
      s("Cat Esterilizado", "gatos", "7 kg", 0),
      s("Cat Kitten", "gatos", "7 kg", 0),
      s("Canis", "perros", "12 kg", 0),
    ],
  },
  {
    brand: "PLOPLAN",
    items: [
      s("Obesity 12kg", "perros", "12 kg", 0),
      s("Hipoalergénico 12kg", "perros", "12 kg", 1),
      s("Neurocare 3kg", "perros", "3 kg", 1),
      s("Obesity 3kg", "perros", "3 kg", 1),
    ],
  },
  {
    brand: "HARPER AND BONES",
    items: [
      s("Fresh", "perros", "12 kg", 1),
      s("Wild", "perros", "12 kg", 3),
      s("Ocean", "perros", "12 kg", 1),
      s("Amanova Cerdo", "perros", "12 kg", 0),
      s("Amanova Conejo", "perros", "12 kg", 0),
      s("Amanova Pavo Obesity", "perros", "12 kg", 1),
      s("Amanova Salmón", "perros", "12 kg", 1),
      s("Mini Pollo Amanova", "perros", "10 kg", 0),
      s("Mini Wild 10kg", "perros", "10 kg", 0),
    ],
  },
  {
    brand: "SELECT",
    items: [
      s("Salmón", "perros", "12 kg", 1),
      s("Lamb", "perros", "12 kg", 1),
      s("Light", "perros", "12 kg", 1),
      s("Pollo", "perros", "12 kg", 2),
      s("Hipoalergénico", "perros", "12 kg", 1),
      s("Cat No Grain 8kg", "gatos", "8 kg", 0),
      s("Renal 8kg", "perros", "8 kg", 1),
      s("Urinary", "perros", "12 kg", 1),
    ],
  },
  {
    brand: "ADVANCE",
    items: [
      s("Esterilizado 10kg Pavo", "perros", "10 kg", 0),
    ],
  },
  {
    brand: "LIBRA",
    items: [
      s("Salmón 14kg", "perros", "14 kg", 3),
      s("Buey 14kg", "perros", "14 kg", 0),
      s("Lamb 14kg", "perros", "14 kg", 1),
      s("Pollo 14kg", "perros", "14 kg", 0),
      s("Light 12kg", "perros", "12 kg", 3),
      s("Urinary 8kg", "perros", "8 kg", 0),
    ],
  },
  {
    brand: "TRAINERS",
    items: [
      s("Salmón 12kg", "perros", "12 kg", 0),
      s("Buey 12kg", "perros", "12 kg", 0),
      s("Pollo 12kg", "perros", "12 kg", 0),
      s("Oke Gato", "gatos", "", 0),
    ],
  },
  {
    brand: "OWNAT",
    items: [
      s("Pollo", "perros", "12 kg", 1),
      s("Mini", "perros", "3 kg", 0),
      s("Lamb", "perros", "12 kg", 2),
      s("Fish", "perros", "12 kg", 1),
      s("Light", "perros", "12 kg", 0),
    ],
  },
  {
    brand: "SERECTO",
    items: [
      s("Sereco GR", "perros", "", 6),
      s("Sereco CH", "perros", "", 13),
    ],
  },
  {
    brand: "TUSSEL",
    items: [
      s("Tussel", "perros", "", 1),
    ],
  },
  {
    brand: "DIETISUR",
    items: [
      s("Carbonato Magnesio Neutro", "vitaminas", "", 3),
      s("Carbonato Magnesio Fresa", "vitaminas", "", 3),
      s("Aceite de Almendras 1L", "otros", "1 L", 1),
      s("Aceite de Almendras 250ml", "otros", "250 ml", 2),
      s("Ortosifón", "digestion", "", 1),
      s("Levadura + Germen", "vitaminas", "", 3),
      s("Pasiflora Gota", "descanso", "", 0),
      s("Eufrasia", "plantas", "", 2),
      s("Enzimas", "digestion", "", 0),
      s("Papaya", "digestion", "", 6),
      s("Mielicina Garganta", "digestion", "", 1),
      s("Uña de Gato", "plantas", "", 1),
      s("Omega 3 50p", "omega", "50 cápsulas", 8),
      s("Vinagre de Manzana Caps.", "digestion", "", 1),
      s("Isoflavona", "plantas", "", 3),
      s("Aceite de Bacalao", "omega", "", 1),
      s("Glucomanano", "quemagrasas", "", 0),
      s("Vinagre de Manzana 1L", "otros", "1 L", 5),
      s("Vinagre de Manzana Madre", "otros", "", 3),
      s("Omega 3-6-9", "omega", "", 2),
      s("Onagra", "omega", "", 2),
      s("Reishi", "plantas", "", 0),
      s("Calcio + D", "vitaminas", "", 1),
      s("Equinácea", "digestion", "", 0),
      s("Floradix", "vitaminas", "", 0),
      s("Jalea Real", "vitaminas", "", 0),
      s("Aceite de Coco 400gr", "otros", "400 g", 2),
      s("Citrato Potasio Nutralie", "vitaminas", "", 4),
      s("Ginseng 90cap", "plantas", "90 cápsulas", 2),
      s("Própolis Forte", "digestion", "", 3),
      s("Women Nutralie", "vitaminas", "", 1),
      s("Sal del Himalaya Molida", "otros", "", 3),
      s("Sal del Himalaya Gruesa", "otros", "", 3),
      s("Cáscara Sagrada", "digestion", "", 1),
      s("Lecitina de Soja 200p", "vitaminas", "200 cápsulas", 0),
      s("Lecitina de Soja 90p", "vitaminas", "90 cápsulas", 1),
      s("Cardo Mariano", "digestion", "", 4),
      s("Men", "vitaminas", "", 0),
      s("Yodo", "vitaminas", "", 2),
      s("Maca Negra", "plantas", "", 3),
      s("Valeriana Gota", "descanso", "", 1),
      s("Cola de Caballo Gota", "plantas", "", 1),
      s("Boldo Comp.", "digestion", "", 1),
      s("Té Verde", "preentrenos", "", 1),
      s("Alcachofa Gota", "digestion", "", 0),
      s("Ron Quina 1L", "digestion", "1 L", 1),
      s("Zinc", "vitaminas", "", 1),
      s("Chitosan + Té Verde", "quemagrasas", "", 1),
      s("Chitosan", "quemagrasas", "", 1),
      s("Cola de Caballo", "plantas", "", 7),
      s("Cup", "vitaminas", "", 1),
      s("Melatonina", "descanso", "", 3),
      s("Curcumina", "digestion", "", 9),
      s("Ashwagandha + MG + Teanina", "plantas", "", 3),
      s("AntiSugar", "quemagrasas", "", 4),
      s("Agua de Rosas 1L", "otros", "1 L", 5),
      s("Guaraná", "preentrenos", "", 2),
      s("Passiflora", "descanso", "", 1),
      s("Liposomal", "vitaminas", "", 2),
      s("Colágeno Nutralie", "colageno", "", 2),
      s("Diente de León", "digestion", "", 2),
      s("Espirulina 100c", "vitaminas", "100 cápsulas", 0),
      s("Espirulina 200c", "vitaminas", "200 cápsulas", 1),
      s("Glucomanano Nutralie", "quemagrasas", "", 1),
      s("Levadura de Cerveza 250c", "vitaminas", "250 cápsulas", 2),
      s("Ginkgo", "plantas", "", 2),
      s("Agua de Mar", "otros", "", 1),
      s("Carbón Activo", "digestion", "", 1),
      s("Ajo 60p", "digestion", "60 cápsulas", 0),
      s("Stevia Polvo", "otros", "", 1),
      s("Garcinia Nutralie", "quemagrasas", "", 0),
      s("Garcinia Sotya", "quemagrasas", "", 0),
      s("Bisglicinato Magnesio", "vitaminas", "", 1),
      s("Té Matcha", "preentrenos", "", 4),
      s("Moringa 9-15", "plantas", "", 5),
      s("Moringa Caps.", "plantas", "", 1),
      s("Árbol del Té 15ml", "otros", "15 ml", 0),
      s("Árbol del Té 30ml", "otros", "30 ml", 0),
      s("Audio Mass", "otros", "", 4),
      s("Poliarticol", "colageno", "", 4),
      s("Glutation Fepa", "vitaminas", "", 1),
      s("Vitamina B50 Fepa", "vitaminas", "", 1),
      s("Fepa Orégano", "digestion", "", 3),
      s("Luteína Fepa", "vitaminas", "", 2),
      s("NADH Fepa", "vitaminas", "", 0),
      s("Clorella Tabletas", "vitaminas", "", 0),
      s("Crema Dental", "otros", "", 3),
      s("Corpore Sano Crema Dental", "otros", "", 3),
      s("Dentífrico", "otros", "", 0),
      s("Mast-Lax", "digestion", "", 1),
      s("Aceite Rosa Mosqueta", "otros", "", 1),
      s("Valeriana + Passiflora", "descanso", "", 1),
      s("Verdes", "vitaminas", "", 58),
      s("Mías Casa", "otros", "", 20),
      s("Sarro Can", "otros", "", 5),
      s("Artic. Can", "colageno", "", 7),
      s("Selenio Fepa", "vitaminas", "", 4),
      s("Melena de León Fepa", "plantas", "", 1),
      s("Teanina Fepa", "descanso", "", 1),
      s("Bone Broth", "colageno", "", 3),
    ],
  },
  {
    brand: "AMIX",
    items: [
      ...v("BCAA + Glutamina 300gr", "300 g", "aminoacidos", [["Neutra", 2], ["Naranja", 1], ["Frutos del Bosque", 1], ["Mango", 2]]),
      s("Alkalyn", "quemagrasas", "", 7),
      s("Multipro Scitec", "proteinas", "", 2),
      s("Hos", "ganadores", "", 0),
      ...v("JUMBO", "3 kg", "ganadores", [["Chocolate", 1], ["Fresa", 0], ["Vainilla", 0]]),
      ...v("Creatina Amix 750gr", "750 g", "creatina", [["Creatina", 6], ["Neutra", 4], ["Lima-Limón", 1], ["Frutos del Bosque", 1]]),
      s("Creapure Amix", "creatina", "", 2),
      s("Creatina Tabletas", "creatina", "", 0),
      s("BCAA Caps.", "aminoacidos", "", 0),
      s("Multimega", "omega", "", 2),
      s("MAP Neutra", "aminoacidos", "", 2),
      s("Thermo Core", "quemagrasas", "", 5),
      s("Hepacor", "digestion", "", 1),
      s("Testo 100 Tabl", "quemagrasas", "100 tabletas", 0),
      s("Testo 200 Caps", "quemagrasas", "200 cápsulas", 3),
      s("Testo 450 Tabletas", "quemagrasas", "450 tabletas", 1),
      s("Cellup Polvo", "quemagrasas", "", 0),
      ...v("YEEP PUMP", "400 g", "preentrenos", [["Lima", 1], ["Naranja", 3], ["Manzana No Stim", 2], ["Piruleta No Stim", 0]]),
      ...v("ISOPRIME 2KG", "2 kg", "proteinas", [["Cookies", 1], ["Frutos del Bosque", 0], ["Fresa", 0], ["Choco Moka", 0]]),
      s("Wazy Maize 2KG", "ganadores", "2 kg", 0),
      s("Creapure X-Up", "creatina", "", 0),
      s("Creapure QuamTrax", "creatina", "", 0),
      s("Creapure Weider", "creatina", "", 7),
      s("HG Hormonal X-Up", "quemagrasas", "", 1),
      s("Detonatrol", "quemagrasas", "", 2),
      s("Resveratrol", "plantas", "", 2),
      s("MoonTruck", "quemagrasas", "", 1),
      s("MoonTruck", "quemagrasas", "", 1),
    ],
  },
  {
    brand: "HARINA ESSENTIAL",
    items: [
      s("Harina de Avena Chocolate Blanco", "ganadores", "1 kg", 1),
      s("Harina de Avena Fresa", "ganadores", "1 kg", 3),
      s("Harina de Avena Plátano", "ganadores", "1 kg", 1),
      s("Harina de Avena Brownie", "ganadores", "1 kg", 0),
      s("Harina de Avena Chocolate", "ganadores", "1 kg", 2),
      s("Harina de Avena Galletas", "ganadores", "1 kg", 2),
      s("Harina de Avena Choc. Avellana", "ganadores", "1 kg", 0),
      s("Harina de Avena Cacahuete", "ganadores", "1 kg", 2),
      s("Harina de Avena KitKat", "ganadores", "1 kg", 2),
      s("Harina de Avena Galletas Chocolate", "ganadores", "1 kg", 0),
      s("Harina de Avena Oreo", "ganadores", "1 kg", 0),
      s("Harina de Avena Fresa/Plátano", "ganadores", "1 kg", 2),
      s("Harina de Avena Vainilla", "ganadores", "1 kg", 0),
    ],
  },
  {
    brand: "CREMA ESSENTIAL",
    items: [
      s("Crema de Avena Natillas", "ganadores", "500 g", 3),
      s("Crema de Avena Chocolate", "ganadores", "500 g", 1),
      s("Crema de Avena Ferrero", "ganadores", "500 g", 3),
    ],
  },
  {
    brand: "CASA SACOS",
    items: [
      s("Libra Light", "perros", "12 kg", 0),
      s("Libra Salmón", "perros", "12 kg", 0),
      s("Libra Buey", "perros", "12 kg", 0),
      s("Libra Lamb 14kg", "perros", "14 kg", 1),
      s("Trainer Adulto Salmón", "perros", "12 kg", 0),
      s("SELECT Light 12kg", "perros", "12 kg", 6),
      s("SELECT Hipoalergénico 10kg", "perros", "10 kg", 1),
      s("SELECT Urinary 8kg", "perros", "8 kg", 0),
      s("SELECT Salmón 12kg", "perros", "12 kg", 20),
      s("SELECT Lamb 12kg", "perros", "12 kg", 16),
      s("Mini Lamb 3kg", "perros", "3 kg", 0),
      s("Mini Lamb 800gr", "perros", "800 g", 6),
      s("Mini Adulto 800gr", "perros", "800 g", 0),
      s("Mini Salmón Select 3kg", "perros", "3 kg", 0),
      s("Mini Light Select 3kg", "perros", "3 kg", 0),
      s("Mini Puppy Select 3kg", "perros", "3 kg", 2),
      s("Kitten 8kg", "gatos", "8 kg", 1),
      s("Esterilizado 8kg", "gatos", "8 kg", 1),
      s("Puppy Pollo", "perros", "12 kg", 0),
      s("Mini Nutrí 10kg", "perros", "10 kg", 5),
      s("Canis", "perros", "12 kg", 0),
      s("Hipoalergénico", "perros", "12 kg", 0),
      s("Nature Pollo", "perros", "12 kg", 0),
      s("Nature Salmón", "perros", "12 kg", 0),
      s("Nutri Light", "perros", "12 kg", 7),
      s("Nutri Lamb 3kg", "perros", "3 kg", 12),
      s("Nutri Cerdo", "perros", "12 kg", 0),
      s("Nutri Salmón", "perros", "12 kg", 0),
      s("Puppy Sensitive 15kg", "perros", "15 kg", 2),
      s("Nutri Pollo 15kg", "perros", "15 kg", 0),
      s("Ownat Lamb", "perros", "12 kg", 3),
      s("Ownat Fish", "perros", "12 kg", 1),
      s("Ownat Pollo", "perros", "12 kg", 0),
      s("Ownat Light", "perros", "12 kg", 0),
      s("Mini Light 3kg", "perros", "3 kg", 0),
      s("Mini Salmón 3kg", "perros", "3 kg", 0),
      s("Mini Lamb 3kg", "perros", "3 kg", 0),
      s("Mini Adulto 3kg", "perros", "3 kg", 0),
      s("Medium Light 3kg", "perros", "3 kg", 0),
      s("Pollo", "perros", "12 kg", 1),
      s("Pavo", "perros", "12 kg", 1),
      s("Fish", "perros", "12 kg", 0),
      s("Pipeta ReforDog 1-4", "perros", "", 0),
      s("Pipeta ReforDog 4-10", "perros", "", 0),
      s("Pipeta ReforDog 10-20", "perros", "", 0),
      s("Pipeta ReforDog 20-40", "perros", "", 0),
    ],
  },
  {
    brand: "PERROS PEQ. · SELECT",
    items: [
      s("Mini Adulto 3kg", "perros", "3 kg", 3),
      s("Mini Salmón 3kg", "perros", "3 kg", 2),
      s("Mini Lamb 3kg", "perros", "3 kg", 0),
      s("Mini Senior 3kg", "perros", "3 kg", 1),
      s("Mini Light 3kg", "perros", "3 kg", 0),
      s("Mini Salmón 800gr", "perros", "800 g", 6),
      s("Mini Lamb 800gr", "perros", "800 g", 2),
      s("Mini Light 800gr", "perros", "800 g", 0),
      s("Mini Puppy 800gr", "perros", "800 g", 2),
      s("Mini Adulto 800gr", "perros", "800 g", 4),
      s("Mini Puppy 3kg", "perros", "3 kg", 2),
      s("Hipoalergénico 2kg", "perros", "2 kg", 0),
      s("Gastrointestinal 2kg", "perros", "2 kg", 1),
    ],
  },
  {
    brand: "PERROS PEQ. · LIBRA",
    items: [
      s("Mini Salmón 3kg", "perros", "3 kg", 4),
      s("Mini Pollo 3kg", "perros", "3 kg", 0),
      s("Lamb 3kg", "perros", "3 kg", 1),
    ],
  },
  {
    brand: "PERROS PEQ. · HARPER AND BONES",
    items: [
      s("Fresh", "perros", "3 kg", 0),
      s("Wild Mini", "perros", "3 kg", 5),
      s("Fresh Mini", "perros", "3 kg", 4),
      s("Amanova Obesity 2kg", "perros", "2 kg", 3),
      s("Amanova Pollo 2kg", "perros", "2 kg", 2),
    ],
  },
  {
    brand: "PERROS PEQ. · NATURE VARIETY",
    items: [
      s("Mini Salmón 1.5kg", "perros", "1.5 kg", 5),
      s("Mini Pollo 1.5kg", "perros", "1.5 kg", 5),
      s("Mini Pavo 1.5kg", "perros", "1.5 kg", 5),
      s("Mini Pescado Blanco", "perros", "1.5 kg", 0),
      s("Mini Puppy Salmón 1.5kg", "perros", "1.5 kg", 0),
      s("Mini Puppy Pollo 3kg", "perros", "3 kg", 0),
      s("Mini Puppy Pollo 1.5kg", "perros", "1.5 kg", 0),
      s("Mini Salmón 3kg", "perros", "3 kg", 1),
      s("Mini Pollo 3kg", "perros", "3 kg", 1),
      s("Mini Pavo 3kg", "perros", "3 kg", 1),
      s("Medium Pavo 3kg", "perros", "3 kg", 1),
      s("Puppy Salmón Mini", "perros", "3 kg", 0),
      s("Medium Salmón 3kg", "perros", "3 kg", 0),
      s("Merluza 3kg", "perros", "3 kg", 0),
      s("Medium Pollo Puppy 3kg", "perros", "3 kg", 1),
      s("Medium Pollo 3kg", "perros", "3 kg", 1),
    ],
  },
  {
    brand: "PERROS PEQ. · ADVANCE",
    items: [
      s("Mini Puppy 700gr", "perros", "700 g", 3),
      s("Mini Puppy 1.5kg", "perros", "1.5 kg", 0),
      s("Mini Puppy 3kg", "perros", "3 kg", 1),
      s("Puppy Sensitive 700gr", "perros", "700 g", 4),
      s("Puppy Sensitive 1.5kg", "perros", "1.5 kg", 0),
      s("Puppy Sensitive 3kg", "perros", "3 kg", 0),
      s("Mini Adulto 700g", "perros", "700 g", 0),
      s("Mini Adulto 1.5kg", "perros", "1.5 kg", 3),
      s("Mini Atópico", "perros", "3 kg", 0),
      s("Mini Adulto 3kg", "perros", "3 kg", 0),
      s("Mini Sensitive 700g", "perros", "700 g", 1),
      s("Mini Sensitive 1.5kg", "perros", "1.5 kg", 2),
      s("Mini Sensitive 3kg", "perros", "3 kg", 4),
      s("Mini Light 1.5kg", "perros", "1.5 kg", 4),
      s("Mini Light 3kg", "perros", "3 kg", 1),
      s("Medium Pollo 3kg", "perros", "3 kg", 0),
      s("Medium Puppy 3kg", "perros", "3 kg", 0),
      s("Medium Sensitive 3kg", "perros", "3 kg", 0),
      s("Diabetes 3kg", "perros", "3 kg", 2),
      s("Urinary 3kg", "perros", "3 kg", 0),
      s("Mini Atopic 3kg", "perros", "3 kg", 1),
      s("Mini Atopic 1.5kg", "perros", "1.5 kg", 1),
      s("Mini Weigh Balance 1.5kg", "perros", "1.5 kg", 2),
      s("Mini Hipoalergénico 2.5kg", "perros", "2.5 kg", 2),
      s("Weigh Balance 3kg", "perros", "3 kg", 1),
      s("Mini Gastrointestinal 3kg", "perros", "3 kg", 1),
      s("Mini Gastrointestinal 1.5kg", "perros", "1.5 kg", 1),
      s("Articular Senior", "perros", "3 kg", 1),
      s("Pato Monoproteico", "perros", "3 kg", 1),
    ],
  },
  {
    brand: "PERROS PEQ. · NUTRIBEST",
    items: [
      s("Salmón 3kg", "perros", "3 kg", 3),
      s("Light 3kg", "perros", "3 kg", 4),
      s("Lamb 3kg", "perros", "3 kg", 4),
    ],
  },
  {
    brand: "PERROS PEQ. · PLOPLAN",
    items: [
      s("Neurocare 3kg", "perros", "3 kg", 1),
      s("Obesity 3kg", "perros", "3 kg", 1),
    ],
  },
  {
    brand: "CAT PEQ. · LARA",
    items: [
      s("Esterilizado", "gatos", "1.5 kg", 3),
      s("Urinary", "gatos", "1.5 kg", 5),
    ],
  },
  {
    brand: "CAT PEQ. · LIBRA",
    items: [
      s("Kitten", "gatos", "1.5 kg", 0),
      s("Pollo", "gatos", "1.5 kg", 1),
      s("Salmón", "gatos", "1.5 kg", 0),
      s("Atún", "gatos", "1.5 kg", 1),
      s("Pollo Esterilizado 1.5kg", "gatos", "1.5 kg", 0),
      s("Urinary 1.5kg", "gatos", "1.5 kg", 0),
      s("Esterilizado Pollo 3kg", "gatos", "3 kg", 2),
      s("Salmón 3kg", "gatos", "3 kg", 2),
    ],
  },
  {
    brand: "CAT PEQ. · SELECT",
    items: [
      s("Salmón", "gatos", "1.5 kg", 0),
      s("Urinary", "gatos", "1.5 kg", 1),
      s("Pollo Esterilizado 2kg", "gatos", "2 kg", 2),
      s("Renal 2kg", "gatos", "2 kg", 0),
    ],
  },
  {
    brand: "CAT PEQ. · ADVANCE",
    items: [
      s("Kitten Esterilizado 1.5kg", "gatos", "1.5 kg", 1),
      s("Esterilizado 3kg Salmón", "gatos", "3 kg", 1),
      s("Renal 1.5kg", "gatos", "1.5 kg", 0),
      s("Hipoalergénico 1.5kg", "gatos", "1.5 kg", 0),
      s("Gastrointestinal 3kg", "gatos", "3 kg", 0),
      s("Urinary 1.5kg", "gatos", "1.5 kg", 3),
      s("Urinary 3kg", "gatos", "3 kg", 1),
      s("Weigh Balance 3kg", "gatos", "3 kg", 1),
    ],
  },
  {
    brand: "CAT PEQ. · PLOPLAN",
    items: [
      s("Obesity 1.5kg", "gatos", "1.5 kg", 2),
      s("Urinary 5kg", "gatos", "5 kg", 0),
      s("Gastrointestinal 5kg", "gatos", "5 kg", 3),
      s("Gastrointestinal 1.5kg", "gatos", "1.5 kg", 0),
      s("Renal 5kg", "gatos", "5 kg", 0),
    ],
  },
  {
    brand: "CAT PEQ. · TRAINERS",
    items: [
      s("Kitten 1.5kg", "gatos", "1.5 kg", 3),
      s("Exigen 1.5kg", "gatos", "1.5 kg", 0),
      s("Pollo 1.5kg", "gatos", "1.5 kg", 1),
      s("Atún 1.5kg", "gatos", "1.5 kg", 1),
      s("Salmón Esterilizado 1.5kg", "gatos", "1.5 kg", 5),
      s("Pavo 1.5kg", "gatos", "1.5 kg", 1),
      s("Fish 1.5kg", "gatos", "1.5 kg", 1),
    ],
  },
  {
    brand: "CAT PEQ. · HARPER AND BONES",
    items: [
      s("Esterilizado 2kg", "gatos", "2 kg", 0),
      s("Flavours 2kg", "gatos", "2 kg", 0),
      s("Fresh 2kg", "gatos", "2 kg", 1),
      s("Wild 2kg", "gatos", "2 kg", 5),
      s("Kitten 2kg", "gatos", "2 kg", 3),
      s("Flavour 5kg", "gatos", "5 kg", 0),
      s("Ocean Wonder 5kg", "gatos", "5 kg", 0),
      s("Wild 5kg", "gatos", "5 kg", 2),
      s("Fresh 5kg", "gatos", "5 kg", 0),
    ],
  },
  {
    brand: "CAT PEQ. · NATURE VARIETY",
    items: [
      s("Kitten 1.25kg", "gatos", "1.25 kg", 1),
      s("Salmón 1.2kg", "gatos", "1.2 kg", 0),
      s("Pollo 3kg", "gatos", "3 kg", 1),
      s("Salmón 3kg No Grain", "gatos", "3 kg", 1),
      s("Salmón 3kg Bajo Cereales", "gatos", "3 kg", 1),
      s("Pavo 3kg", "gatos", "3 kg", 0),
      s("Kitten 3kg", "gatos", "3 kg", 1),
      s("Pescado Blanco 3kg", "gatos", "3 kg", 0),
    ],
  },
  {
    brand: "CASA NUTRICIÓN",
    items: [
      ...v("ISO2KG", "2 kg", "proteinas", [["Ferrero", 0], ["Donuts", 0], ["Hel. Vainilla", 0], ["Chocolate Blanco", 0], ["KitKat", 0], ["Fresa", 0], ["Piña", 0], ["Cookies", 0], ["Fresa/Plátano", 0], ["Vainilla Canela", 0], ["Donuts Chocolate", 0], ["Chocolate", 0], ["Limón", 0], ["Donuts Chocolate Blanco", 0], ["Oreo", 0], ["Plátano", 0], ["Cookies Chocolate Caramelo", 0]]),
      ...v("WHEY 2KG", "2 kg", "proteinas", [["Hel. Vainilla", 0], ["Oreo", 0], ["Chocolate Avellana", 0], ["Fresa/Plátano", 0], ["Limón", 0], ["KitKat", 0], ["Cookies", 0], ["Vainilla Canela", 0], ["Choco Blanco", 0], ["Chocolate", 0], ["Ferrero", 0], ["Plátano", 0], ["Fresa", 0], ["Piña", 0], ["Colágeno Limón", 0]]),
      ...v("CASEÍNA", "1 kg", "proteinas", [["Chocolate", 0], ["Vainilla", 0], ["Fresa/Plátano", 0]]),
      ...v("GAINERS 3KG", "3 kg", "ganadores", [["Chocolate", 0], ["Chocolate Blanco", 0], ["Cookies", 0], ["Fresa", 0], ["Vainilla Canela", 0]]),
      s("Vitamina D3+K2", "vitaminas", "", 0),
      s("R-ALA", "quemagrasas", "", 0),
      ...v("HARINA AVENA", "1 kg", "ganadores", [["Chocolate Blanco", 1], ["Chocolate", 0], ["Cacahuete", 0], ["KitKat", 0], ["Fresa", 3], ["Cookies", 1], ["Neutra", 0], ["Fresa-Plátano", 0], ["Plátano", 1]]),
      ...v("CREAPURE", "300 g", "creatina", [["Neutra", 0], ["Piruleta", 0]]),
      s("Creatina Piruleta", "creatina", "", 0),
      s("Creatina Limón", "creatina", "", 0),
      s("Creatina Naranja", "creatina", "", 0),
      s("Creatina Neutra", "creatina", "", 0),
      s("Burn Core 30", "quemagrasas", "30 cápsulas", 0),
      s("Burn Core 90", "quemagrasas", "90 cápsulas", 5),
      s("CLA", "quemagrasas", "", 0),
      s("Tribulus", "quemagrasas", "", 0),
      s("Multivitamínico", "vitaminas", "", 12),
      s("Senefrina", "quemagrasas", "", 0),
      s("Gummy", "descanso", "", 0),
      s("One 30", "otros", "30 cápsulas", 0),
      s("Water", "otros", "", 0),
      s("NAC", "digestion", "", 6),
      s("Burn Core 30p", "quemagrasas", "30 cápsulas", 0),
      s("Omega 3", "omega", "", 0),
      s("ZMA", "vitaminas", "", 0),
      s("Testo 90", "quemagrasas", "", 5),
      s("Ashwagandha Sensoril", "plantas", "", 0),
      ...v("ISO 1KG", "1 kg", "proteinas", [["Limón", 0], ["Piña", 0], ["KitKat", 0], ["Vainilla Canela", 0], ["Hel. Vainilla", 0], ["Chocolate Avellana", 0], ["Cookies Choc. Caramelo", 0], ["Ferrero", 0], ["Chocolate", 0], ["Chocolate Blanco", 0], ["Cookies", 0], ["Donuts", 0], ["Donuts Chocolate", 0], ["Donuts Chocolate Blanco", 0], ["Fresa", 0], ["Fresa/Plátano", 0], ["Plátano", 0], ["Oreo", 0]]),
      ...v("WHEY 1KG", "1 kg", "proteinas", [["Chocolate Blanco", 0], ["KitKat", 0], ["Chocolate", 0], ["Donuts Choc. Blanco", 0], ["Donuts", 0], ["Fresa", 0], ["Ferrero", 0], ["Cookies", 0], ["Fresa/Plátano", 0], ["Limón", 0], ["Plátano", 0], ["Oreo", 0], ["Piña", 0], ["Vainilla Canela", 0], ["Hel. Vainilla", 0], ["Chocolate Avellana", 0]]),
      ...v("MAP", "350 g", "aminoacidos", [["Melocotón", 0], ["Cola", 0], ["Piruleta", 0], ["Naranja", 0]]),
      ...v("PUMP", "400 g", "preentrenos", [["Sandía", 0]]),
    ],
  },
];
